import Head from 'next/head';
import { Inter } from '@next/font/google';
import TheHeader from '../components/TheHeader';
import About from '../components/About';
import Contact from '../components/Contact';
import Experience from '../components/Experience';
import Hero from '../components/Hero';
import TheFooter from '../components/TheFooter';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TheHeader />
        <About />
        <Contact />
        <Experience />
        <Hero />
        <TheFooter />
      </main>
    </>
  );
}
